#!/usr/bin/python3

if [ -z "$PYFILE" ]; then
    echo "PYFILE environment variable is not set."
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "File specified in PYFILE does not exist."
    exit 1
fi

python3 "$PYFILE"

